micronaut:
  application:
    name: clienteServer
#datasources:
#  default:
#    url: jdbc:h2:mem:devDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
#    username: 'sa'
#    password: ''
#    driver-class-name: org.h2.Driver
#    dialect: H2

datasources:
  default:
    url: ${JDBC_URL:'jdbc:mysql://localhost:3306/cliente-db'}
    username: ${JDBC_USER:admin}
    password: ${JDBC_PASSWORD:senha}
    driverClassName: "com.mysql.cj.jdbc.Driver"
    dialect: MYSQL


netty:
  default:
    allocator:
      max-order: 3
jpa:
  default:
    packages-to-scan:
      - 'br.com.curso.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true
